### ISSUE TITLE
Installation fails when there are multiple users on the PC

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/SimpleInstaller#30]
別のユーザを取得してしまう

**Comment by matanki-saito** [comment]
https://stackoverflow.com/questions/24822748/shgetfolderpath-returns-path-to-admin-user-account-when-used-in-an-installer

**Comment by matanki-saito** [comment]
確かにローカルアカウントを追加して見ると同様の現象が確認できた。
https://121ware.com/qasearch/1007/app/servlet/relatedqa?QID=017790

**Comment by matanki-saito** [comment]
どうやっても無理

**Comment by matanki-saito** [comment]
これは仕様とする

**Comment by BLACKTIGER-NB** [comment]
closedでwontfixなissueにレスつけるのはどうかとは思う点がありますが、発言します。

これはUACと関連するものと予想します。
pythonならばバッチファイルを二つ作れば解決する可能性があると思います。

> 具体的な方針
> 
> 1.管理者権限でコマンドプロンプトを開き○○というコードを実行するというバッチファイルAを作る
> 2.実行したい○○というコードが書かれたバッチファイルBを作成する
> 3.pythonからバッチファイルAを実行するという指示を飛ばし、本来の目的であるバッチファイルBの内容を実行する
引用元
windowsでpythonから管理者権限が必要なことを実行する方法
https://zerebom.hatenablog.com/entry/2018/12/21/143116

あまり綺麗な方法とは思いませんが、「どうやっても無理」には疑問を持ちましたので発言しました。
以上です。

**Comment by matanki-saito** [comment]
@BLACKTIGER-NB 
お疲れ様です。問題の現象ですが正確に覚えていませんが、UACとは関係がなかったと思います。現象は下記だったはずです。

1.  とあるユーザからインストーラーは正常に終了したが、ランチャーからMODが確認できないと報告があった
2.  確認のためにマイドキュメントのmodフォルダを見てもらったがそこにあるはずのModファイルがなかった
3. 更に確認してみると、そのユーザはPCを家族と共有しており、PCの管理者アカウントは親？で、ユーザはそのPCにローカルアカウントでログインしていた。そして親のマイドキュメントにmodフォルダが作られ、そこにmodが置かれていた。
4. 信じられなかったが、実際に私の環境でローカルアカウントを作成し、そちらでインストーラーを実施したところメインの管理者アカウントにファイルが設置された
5. 色々と調査したが、なぜこのような現象になるのかわからなかったので、一旦ローカルアカウントでは対応しないという方針にした

**Comment by BLACKTIGER-NB** [comment]
返答あったんですね…

ParadoxのゲームのレーティングはTEEN程度を目標としている様子です。
そして、EU4のレーティングはESRB TEENなのでそういったユーザーもいると思います。

一応テストしてみました

1.ローカルアカウントを作ってUACの影響がないフォルダにSteamとEU4をインストール
2.SimpleInstaller Releases 15 でEU4日本語化をインストール
3.無事ローカルアカウントのマイドキュメントフォルダにEU4日本語かMODファイルが作成されて日本語化

ログを見てもちゃんとローカルアカウントのマイドキュメントを取得していました。

このあと、日本語化とEU4とsteamをアンインスールして、UACの影響があるプログラムフォルダ(今回はC:\Program Files (x86))にEU4(とsteam)をインストールしてテストし直そうと思ったんですが問題が発生したので別issueを建てます

テスト環境はWINDOWS10HOME 実機です

**Comment by BLACKTIGER-NB** [comment]
とりあえずSimpleInstaller Releases 15でC:\Program Files (x86)以下にあるEU4を日本語化してみたんですが、
マイドキュメントもちゃんと取得しましたし、UAC要求されることもなく日本語化できました。
このSimpleInstaller Releases 15はUAC要求しませんね。

当時のSimpleInstaller Build: 20190526.1をダウンロードしてみたのですが、起動時にUAC要求してきます。
そして、管理者のマイドキュメントにMODデータが作成されますれます。

SimpleInstaller Releases 15をローカルユーザーから管理者権限(UAC)で起動したところ、
管理者のマイドキュメントパスを取得していました。

やっぱりUACが原因だと思うんですが、どうでしょうね。
