### ISSUE TITLE
Uninstall failure

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/SimpleInstaller#35]
ゲーム
steamのEU4

インストーラー
SimpleInstaller Releases 15

アンインストールが途中で止まります。
ログを見ると、steam板のDLLを削除した後、EPIC板のDLLを削除しようとして失敗してるようです。

おそらく、EPIC板があってsteam板が無いときもSTEAM板のDLLを削除しようとして失敗するのではないかと考えます。
別issueの話題となりますが、ローカルアカウントのマイドキュメントは正常に取得していました。

**Comment by matanki-saito** [comment]
prの送付をお願いします
