### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/SimpleInstaller#8]
そこまで複雑じゃないので中文と韓国、ドイツ語あたり追加しておく

**Comment by matanki-saito** [comment]
https://github.com/matanki-saito/SimpleInstaller/blob/9656de34ba8864835783cdfdfe72fba8af6f0d50/Installer.py#L58

ほげほげ

**Comment by testuser1200** [comment]
書き込みテスト

**Comment by testuser1200** [comment]
[steam_appid.txt](https://github.com/matanki-saito/SimpleInstaller/files/2776282/steam_appid.txt)

**Comment by oooFUNooo** [comment]
修正案ファイル
[messages.txt](https://github.com/matanki-saito/SimpleInstaller/files/2776283/messages.txt)

修正方針（英語）
- not find/exist を was not found に変更
- directory を folder に変更
- game を selected game に変更

修正方針（日本語）
- 語尾を「見つかりませんでした」に統一
- 「ディレクトリ」を「フォルダ」に変更
- 「ゲーム」を「選択したゲーム」に変更

修正対象のコード
https://github.com/matanki-saito/SimpleInstaller/blob/9656de34ba8864835783cdfdfe72fba8af6f0d50/Installer.py#L32-L106
